apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  generateName: load-test-chaos
  namespace: "{{workflow.parameters.adminModeNamespace}}"
  labels:
    instance_id: 1bf60220-0aa9-480a-a51d-1db68bfeb047
    context: load-test-chaos_litmus
    workflow_name: custom-chaos-workflow-1638281927
spec:
  engineState: active
  auxiliaryAppInfo: ""
  chaosServiceAccount: litmus-admin
  jobCleanUpPolicy: retain
  experiments:
    - name: load-test-chaos
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "1m"
            - name: CHAOS_INTERVAL
              value: "30"
            - name: USERS
              value: "100"
            - name: HOST
              value: "http://ec2-3-125-4-65.eu-central-1.compute.amazonaws.com:5005"
            - name: LOAD_TYPE
              value: "load" 
            - name: SPAWN_RATE
              value: "10"
            - name: RESPONSE_TYPE
              value: "token"
            - name: CM_FILE
              value: "/tmp/get/config.py"
            - name: GRANT_TYPE
              value: "client_credentials"
            - name: NODE_NAMES  
              value: ""
            - name: REPLICA
              value: "1"
            - name: LOAD_IMAGE 
              value: "kaleoum/kgh-load:test-tools"
        probe: []
  annotationCheck: "false"
